### ISSUE TITLE
敵機制作依頼

### ISSUE THREAD

**Issue by hungrykirby** [AStudy/Tokko#1]
自機に関しては、動きを完成させました。またスペースキーで球が出るようになっています。自機の当たり判定は未実装です。
敵機の球に当たり判定プログラムを書いてください。それをもとに自機が破壊されゲームオーバーとなるようにしてください。ゲームオーバーという表示が画面上に出る必要は今のところないと思いますが、余力があればお願いします。
また自機から発射された球か敵機に当たり判定プログラムを追加して、両者が当たったら、消えるようにしてください。

**Comment by Okuya** [comment]
敵機の表示と弾の発射、弾の当たり判定を実装したのでコミット・プッシュしました。
