### ISSUE TITLE
画像の読み込みにcsvを用いる

### ISSUE THREAD

**Issue by Okuya** [AStudy/Tokko#10]
今の実装では読み込む画像をコード上で直接指定していますが、このままだと画像の枚数が増えてくると
コードがやたら長くなりそうです。
csvファイルに画像の一覧を記述し、それを使って画像を読み込むように変更しましょう。
（本当はdataフォルダのファイル一覧を取得し、そこから画像を読み込むようにしたいのですが、
Processingでは実行中のpdeファイルのパスを取得できないので無理そうです。）

**Comment by hungrykirby** [comment]
実装しました。確認お願いします。
A1に自機の画像。A2～に敵機の画像の名前を配置させるようにしています。B~1に背景画像の名前を配置予定です。

**Comment by Okuya** [comment]
確認しました。たぶんcsvのコミット忘れが原因でエラーになってます。

**Comment by hungrykirby** [comment]
申し訳ありません。pushしました。

**Comment by Okuya** [comment]
動いたのを確認しました。
ちょっと気になったんですが、ハッシュのキーをファイル名とは別の独自の文字列に設定してるのって
どういう目的で行ってるんでしょうか？
この実装だと、例えば敵の画像に「B-29.png」というのを用いる場合、ハッシュからこの画像を取得するときに
このファイル名がどのようなキーに変換されたのか調べる手間がかかるので、デメリットの方が大きい気がします。

**Comment by hungrykirby** [comment]
それは画像の名前は「jikijet.bmp」だけどハッシュのキーは「jikiJet」なのはどうしてか、ということですか？
すみません、特に大きい理由はないんですけど、自機＋Jetだと思って、jetのjを大文字にしてしまいました。

**Comment by Okuya** [comment]
いや、もっと根本的な問題で、「B-29.png」とか「F4F.png」という画像を使っても、
全て「tekiJet（整数）」というキーになる仕様についてです。

**Comment by hungrykirby** [comment]
想定していなかったので、修正してpushしておきました。

**Comment by Okuya** [comment]
確認しました。
この実装だと、imagesの全てのキーをハードコーディングする必要があるので、
このissueの目的を果たせてないです。
画像を追加してcsvを書き換えたものをプッシュしたので、TOKKO.pde内ではキーを一切
ハードコーディングすることなく、全ての画像を読み込んでください。

**Comment by hungrykirby** [comment]
確認しました。
このissueの目的を理解できていませんでした。修正します。

**Comment by hungrykirby** [comment]
実装しました。確認お願いします。
hashのキーは画像の拡張子を除いたものを採用していますが、拡張子は除くべきですか？除かないべきですか？

**Comment by Okuya** [comment]
除く処理が増えてコードが複雑になるので、除くべき理由がなければ、拡張子は除かない方がいいと思います。

**Comment by hungrykirby** [comment]
わかりました。修正したものをpushします。

**Comment by hungrykirby** [comment]
修正したものをpushしました。確認お願いします。

**Comment by Okuya** [comment]
確認しました。
setup関数が長くなってきたので、画像の読み込み処理を関数化して、setupからの分離をお願いします。

**Comment by Okuya** [comment]
分離処理は #17 でまとめて修正してもらったので、次のことを書きます。
TOKKO.pde の画像読み込みの部分で先頭にPのついた変数名がいくつかありますが、
これってどういう意味でしょうか？ 変数名がキャメル記法になってないのも気になります。

**Comment by hungrykirby** [comment]
キャメルケースでないのはミスです。
ProcessingにはPGraphicsやPImageのように大文字Pで始まるものが、あってそれに従いましたが、これらのPはProcessingのPで、今回のPはplaneのPなので大文字にする理由がないと思いました。修正します。

**Comment by Okuya** [comment]
Processingでは「クラス名」の先頭にPが付いていて、これらのクラスがProcessingの標準のクラスであることが一目で分かるようになっています。
ところが、今回の関数では「変数名」に全てpが付いているのですが、これって本当に必要でしょうか？

**Comment by hungrykirby** [comment]
planeのpをつけて、csv[][]をグローバル変数にしたくなったときに対処できるようにしました。

**Comment by Okuya** [comment]
グローバル変数の利用はできるだけ避けた方がよいというのがプログラミングの一般論ですが、
今回のケースでグローバル変数化を準備しないといけない要因ってあるんでしょうか？

**Comment by hungrykirby** [comment]
参考にしたサイトがグローバル変数で用意していたため、それに備えましたが、必要なさそうなので修正します。

**Comment by Okuya** [comment]
確認しました。
あと、 #17 と同様に、こちらもアルゴリズムを整理できると思います。

**Comment by hungrykirby** [comment]
修正しました。確認お願いします。
飛行機の名前を縦にひたすら並べるだけだと想定して、より縮小させました。

**Comment by Okuya** [comment]
確認しました。

＞＞飛行機の名前を縦にひたすら並べるだけだと想定して、より縮小させました。
現状のcsvの内容と一致しているので、今はこれでいいと思います。

あと、不要な変数が残っているのでそれを削除するのと、、このfor文ではfor-eachを使うようにしてください。

**Comment by Okuya** [comment]
すいません、確認ミスでした。
不要な変数は既に削除されているので、for-eachの方だけでいいです。

**Comment by hungrykirby** [comment]
了解しました。風邪でしばらく浮上できず申し訳ないです。

**Comment by hungrykirby** [comment]
二か所for-each文に修正しました。ご確認ください。

**Comment by Okuya** [comment]
確認しました。Closeします。
