### ISSUE TITLE
画像の透過

### ISSUE THREAD

**Issue by hungrykirby** [AStudy/Tokko#12]
敵機や自機の画像の背景が透過されていないので、修正したものを作成してください。

**Comment by Okuya** [comment]
確認しました。

作業してコミット・プッシュしたら必ずissueに書き込みをお願いします。
書き込みがあると、メールで通知が送られ、作業内容を確認することができます。

また、コミットの際のメッセージには必ずissueの名前と番号の記入をお願いします。
これがないと、あとからログを見たときに、対応するissueの把握ができなくなります。
メッセージの書き方は、これまでのコミットのログを参考にしてください。

**Comment by hungrykirby** [comment]
確認しました。closeします。
