### ISSUE TITLE
敵が出る前から画面の左右端に敵ミサイルが出続けるバグ

### ISSUE THREAD

**Issue by hungrykirby** [AStudy/Tokko#14]
敵が出る前から画面の左右端に敵ミサイルが出続けるバグを解消し、敵がいるところから＋敵が出たタイミングより後にミサイルが出るようにしてください。

**Comment by Okuya** [comment]
修正したので確認をお願いします。

**Comment by hungrykirby** [comment]
確認しました。closeします。
