### ISSUE TITLE
tokkoData.csvから敵機を作成する処理の関数化

### ISSUE THREAD

**Issue by Okuya** [AStudy/Tokko#17]
setup関数が長くなってきたので、tokkoData.csvから敵機を作成する処理を関数化して、setup関数からの
分離をお願いします。

**Comment by yukihiroo** [comment]
できました。確認お願いします。

**Comment by Okuya** [comment]
確認しました。
関数名ですが、「動詞から始まる」の原則に従って、「createEnemies」、「createImages」がいいと思います。
また、これらの関数はsetup()のみで用いて他で使い回さないことから、どのcsvを用いるかは関数内部で
ハードコーディングしても問題が無いので、loadStrings("tokkoData.csv")は引数ではなく関数の内側に
移動した方がコードが読みやすいと思います。

**Comment by Okuya** [comment]
すいません、直前のコメントを修正しました。
使い回す→使い回さない

**Comment by hungrykirby** [comment]
createImageという関数はすでにprocessing内にあるようなので、createImagesに変更しました。それに伴って、createEnemyをcreateEnemiesに変更しました。確認お願いします。

**Comment by Okuya** [comment]
確認しました。
今回は画像も敵機も複数作成しているので、複数形のcreateImagesとcreateEnemiesで正解です。

**Comment by Okuya** [comment]
createEnemies 関数の内部で csv ファイルから読み込んだ情報を全て String[][] csv という配列に
コピーしていますが、この処理って必ず必要なものでしょうか？
おそらく下記のアルゴリズムでも同じ処理がシンプルに実装できると思います。

```
for (string[] csvファイルの全ての行)
｛
    csvファイルの1行を取得 → string
    1行を ',' で分割 → string[]
    文字列を数値に変換
    　・・・
    文字列を数値に変換
    数値から敵機を作成
    敵機をArrayListに追加
｝
```

**Comment by hungrykirby** [comment]
修正しました。ご指摘ありがとうございます。

**Comment by Okuya** [comment]
確認しました。
あと、文字列から数への変換ですが、
Float.valueOf().floatValue() を使うより、
parseFloat(), parseInt() を使った方がよくないですか？

**Comment by hungrykirby** [comment]
確かにその通りです。修正しました。

**Comment by Okuya** [comment]
2/3 の 0:01のコメントですが、ステージ毎に読み込むcsvは変わるので、
csvのパスをハードコーディングするのは駄目でした。
背景など敵機以外の情報をcsvに追加することを考えると、createEnemyes()には
文字列の配列を渡すのが正解みたいです。

**Comment by Okuya** [comment]
作業が一通り完了しているようなのでCloseします。
