### ISSUE TITLE
AimingEnemyは自機が移動しないと当たらない。

### ISSUE THREAD

**Issue by hungrykirby** [AStudy/Tokko#19]
ホーミング弾は自機が移動しないと一切当たりません。そのバグを解決してください。

**Comment by Okuya** [comment]
修正したものをコミットしたので確認をお願いします。
ちなみに、この弾は相手の方向に向けて撃ってるだけで追尾はしてないので、ホーミングとは言わないです。

**Comment by hungrykirby** [comment]
確認しました。また日本語の修正ありがとうございます。Closeします。
