### ISSUE TITLE
出てきていない敵が自機を狙った球を撃ってくる

### ISSUE THREAD

**Issue by hungrykirby** [AStudy/Tokko#21]
出てきていない敵が自機を狙った球を撃ってきます。これは仕様でしょうか。バグでしょうか。バグにしても仕様にしても修正してください。難易度が高すぎるように感じます。

**Comment by Okuya** [comment]
確認したところ、出てきてない敵が撃っているのではなく、敵機と弾の位置が合っていないみたいです。
全ての弾が左右端から出現しています。
原因はEnemyクラスのメンバ変数x, yの扱いの違いにあるようです。
AimingEnemyクラスのaddMissileではEnemyのx, y を現在の位置として利用しているのに対し、
それ以外のクラスではx. y を初期位置として利用しています。
また、それらのクラスでは、Enemyの現在の位置は必要なときに計算しているので、
メンバ変数としては保持してないです。

これは仕様を統一する必要がありますが、
・Enemyのメンバのx, y を現在の位置として用いる
・x,y は初期位置として利用して、現在の位置はメンバ変数として保持しない
とでは、どちらがよいでしょうか？

@yukihiroo 
Enemyのx.yを初期位置として利用して現在の位置は計算で求める方式が最初に用いられたのは
2月1日の　２秒ごとに敵の出てくるゲームの作成 (#11)　 e7bb411a85862f7ab3ed03d464f789207b738f2e 
からのようですが、x,yの扱いをこのようにしたのって、何か理由があるんでしょうか？

**Comment by yukihiroo** [comment]
現在の位置は計算で求める方式にした理由は2/1のプログラムから、初めて敵機が動くようになったからです。2/1以前のプログラムでは敵機は静止しています。
この方式じゃなきゃいけないという特別な理由がないので、Enemyのメンバのx, y を現在の位置として用いる方式で構いません。

**Comment by Okuya** [comment]
Enemyのメンバのx, y を現在の位置として利用するように変更しました。
この変更で標題のバグも修正されています。

**Comment by hungrykirby** [comment]
確認しました。ありがとうございます。
