### ISSUE TITLE
動画をリバースエンジニアリングしたプログラム

### ISSUE THREAD

**Issue by hungrykirby** [AStudy/Tokko#22]
動画を模倣したゲームの作成にあたって、今のtokkoData.csvファイルの形(1出現時間(t) 2出現場所(x) 3出現場所(y) 4スピード(s) 5動きの種類(type) 6動きの方向(direction))だけで十分でしょうか。もし、十分でない場合はcsv_manual.txtを修正してください。

**Comment by Okuya** [comment]
確認していて気付いたのですが、tokkoData.csv　と csv_manual.txt の内容が一致していないです。
2つのファイルで列の数が異なります。
Exelの列の数え方がA,B,C,...なのに、csv_manual.txt　を1,2,3,...で記述してしまったのが、
このミスの根本的な原因ではないかと思います。

**Comment by hungrykirby** [comment]
ご指摘ありがとうございます。

@yukihiroo 
上記指摘をふまえつつ、csv_manual.txtを修正してください。

**Comment by yukihiroo** [comment]
確認お願いします。

**Comment by Okuya** [comment]
txtを確認しました。

**Comment by Okuya** [comment]
これまでの位置決定の方法とcsvの書き方では動画の動きはできそうになかったので、
#23 に動きのためのissueを作成しました。
それに伴ってステージ設定の csv の書き方を変更したものをコミットしました。
内容がかなり変更されているので、各自で確認をお願いします。

**Comment by hungrykirby** [comment]
確認しました。このissueはクローズします。
