### ISSUE TITLE
記法をキャメルケースで統一する

### ISSUE THREAD

**Issue by Okuya** [AStudy/Tokko#5]
一つのソースファイルの中にキャメルケースとスネークケースが混在しているので、
Java標準のキャメルケースに統一する。

**Comment by Okuya** [comment]
Myplaneクラスのクラス名とファイル名も修正をお願いします。
クラス名はアッパーキャメルケース、ファイル名はクラス名と同じものです。

**Comment by Okuya** [comment]
確認しました。
ファイル名の修正もお願いします。
差分を追うため、ファイル名の変更はTortoiseGit上から行ってください。

**Comment by hungrykirby** [comment]
確認しました。
ご指摘ありがとうございます。

**Comment by Okuya** [comment]
確認しました。myPlane.pdeのファイル名も修正をお願いします。

**Comment by hungrykirby** [comment]
myPlaneに関しては、名前を普通に変更してしまったため、こちらから見ると変更されているので、変更できません。そちらから変更してもらっていいですか？

**Comment by Okuya** [comment]
これ、Windowsの機能で名前を元に戻してから、TortoiseGitの機能で名前を変更すると反映されます。
Windowsではファイル名の大文字と小文字を区別しないのですが、Gitは大小を区別するので、
このような現象が起きるみたいです。

**Comment by hungrykirby** [comment]
なるほど。そうなんですか、以後名前の変更は気をつけます。
修正しました。確認お願いします。

**Comment by Okuya** [comment]
確認しました。closeします。
