### ISSUE TITLE
画像をHashMapで保持する

### ISSUE THREAD

**Issue by Okuya** [AStudy/Tokko#8]
今は画像毎に変数を用意していますが、このままだと画像が増える度に変数が増えそうです。
使用する画像は全て1つのHashMapで保持するのがいいと思います。
HashMap<String, PImage> images;

**Comment by Okuya** [comment]
確認しました。

`import java.util.Map;`
HashMap は Processing の標準の機能なので import しなくても使えるはずですが、
何故 import されているんでしょうか？
あと、今回の変更で不要になった変数が残っているので、これは削除していいと思います。

**Comment by hungrykirby** [comment]
ご指摘ありがとうございます。

いろいろ試していた痕跡を残してしまいました。削除しておきます。

**Comment by Okuya** [comment]
確認しました。
一通り完了しているので、このissueはクローズしときます。

＞いろいろ試していた痕跡を残してしまいました。削除しておきます。
こういう痕跡ってうっかり残してしまうことが多いので（僕も）、コミット前に差分を確認する習慣をつけるのが良いです。
